// <auto-generated />
using GestorIAAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorIAAS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909181239_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GestorIAAS.Models.RegistroIAAS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Microorganismo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroIAAS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicioClinicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoIAASId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServicioClinicoId");

                    b.HasIndex("TipoIAASId");

                    b.ToTable("RegistrosIAAS");
                });

            modelBuilder.Entity("GestorIAAS.Models.ServicioClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiciosClinicos");
                });

            modelBuilder.Entity("GestorIAAS.Models.TipoIAAS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificaMinsal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TiposIAAS");
                });

            modelBuilder.Entity("GestorIAAS.Models.RegistroIAAS", b =>
                {
                    b.HasOne("GestorIAAS.Models.ServicioClinico", "ServicioClinico")
                        .WithMany("Registros")
                        .HasForeignKey("ServicioClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorIAAS.Models.TipoIAAS", "TipoIAAS")
                        .WithMany("Registros")
                        .HasForeignKey("TipoIAASId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicioClinico");

                    b.Navigation("TipoIAAS");
                });

            modelBuilder.Entity("GestorIAAS.Models.ServicioClinico", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("GestorIAAS.Models.TipoIAAS", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
